language: node_js
node_js:
- 10
addons:
  ssh_known_hosts: kulturspektakel.de
before_install:
  - openssl aes-256-cbc -K $encrypted_869f24d24cf0_key -iv $encrypted_869f24d24cf0_iv
    -in deploy_rsa.enc -out ./deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_rsa
  - ssh-add ./deploy_rsa
script:
  - echo "done"
deploy:
  provider: script
  skip_cleanup: true
  script: ssh kultwiki@kulturspektakel.de 'cd html && git pull origin master'
  on:
    branch: master
