language: php
php:
  - 7.2
addons:
  ssh_known_hosts: kultursp.uber.space
before_install:
  - openssl aes-256-cbc -K $encrypted_869f24d24cf0_key -iv $encrypted_869f24d24cf0_iv
    -in deploy_rsa.enc -out ./deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_rsa
  - ssh-add ./deploy_rsa
  - rm ./deploy_rsa
script:
  - composer install
  - yarn
  - yarn gulp
  - rm -rf content node_modules media site/cache
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -av $TRAVIS_BUILD_DIR/ kultursp@kultursp.uber.space:html && ssh kultursp@kultursp.uber.space 'rm -rf html/site/cache'
  on:
    branch: master
