# The site blueprint must have a title, the title may be different from the file name
# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
title: Dashboard

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:

tabs:
  inhalte:
    columns:
      - width: 2/3
        sections:
          posts:
            extends: sections/news
            type: pages
            template:
              - news

      - width: 1/3
        sections:
          seiten:
            type: pages
            create: default
  infos:
    columns:
      - width: 1/2
        sections:
          info:
            type: fields
            label: Published on
            fields:
              eventdate:
                label: Kult-Datum (Freitag)
                type: date
                time: false
              infotext:
                label: Beschreibungstext
                type: textarea
      - width: 1/2
        sections:
          info2:
            type: fields
            label: Published on
            fields:
              footerlinks:
                label: Links im Footer
                type: textarea
              sociallinks:
                label: Social Media Links
                type: textarea
  preislisten:
    columns:
      - width: 1/1
        sections:
          buden:
            type: fields
            fields:
              preislisten:
                type: structure
                fields:
                  name:
                    label: Budenname
                    type: text
                    required: true
                  devices:
                    label: Geräte
                    type: tags
                  products:
                    label: Produkte
                    type: structure
                    fields:
                      productname:
                        label: Produktname
                        type: text
                        width: 3/4
                        required: true
                      price:
                        label: Preis
                        type: number
                        step: 0.5
                        width: 1/4
                        required: true
                        align: right
                        after: "Euro"
