# The site blueprint must have a title, the title may be different from the file name
# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
title: Dashboard

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:

tabs:
  inhalte:
    columns:
      - width: 2/3
        sections:
          posts:
            extends: sections/news
            type: pages
            template:
              - news

      - width: 1/3
        sections:
          seiten:
            type: pages
            create: default
  infos:
    columns:
      - width: 1/2
        sections:
          info:
            type: fields
            label: Published on
            fields:
              eventdate:
                label: Kult-Datum (Freitag)
                type: date
                time: false
              infotext:
                label: Beschreibungstext
                type: textarea
      - width: 1/2
        sections:
          info2:
            type: fields
            label: Published on
            fields:
              footerlinks:
                label: Links im Footer
                type: textarea
              sociallinks:
                label: Social Media Links
                type: textarea
  preislisten:
    columns:
      - width: 2/3
        sections:
          preislisten:
            type: fields
            fields:
              buden:
                label: Preislisten
                type: structure
                sortable: false
                sortBy: name
                columns:
                  name:
                    width: 1/4
                  products:
                    width: 3/4
                fields:
                  name:
                    label: Bude
                    type: text
                    required: true
                  products:
                    label: Produkte
                    type: structure
                    sortable: true
                    columns:
                      name:
                        width: 3/4
                      price:
                        width: 1/4
                        after: €
                        align: right
                    fields:
                      name:
                        label: Name
                        type: text
                        required: true
                        width: 3/4
                      price:
                        label: Preis
                        type: number
                        required: true
                        width: 1/4
                        after: €
                        step: 0.5
                        min: 0.5
      - width: 1/3
        sections:
          devices:
            type: fields
            fields:
              devices:
                label: Geräte
                type: structure
                sortable: false
                sortBy: id
                fields:
                  id:
                    label: Geräte ID
                    type: text
                    placeholder: 00:00:00
                    required: true
                    converter: upper
                    validate:
                      match: '/[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}$/'
                    minlength: 8
                    maxlength: 8
                  bude:
                    label: Bude
                    type: select
                    options: query
                    query:
                      fetch: site.Buden.toStructure
                      text: '{{ structureItem.name }}'
                      value: '{{ structureItem.name }}'
